[package]
name = "nats-async"
version = "0.1.0"
edition = "2021"


[dependencies]
tokio = { version = "1", features = ["full"]  }
itoa = "1"
flume = "0.10"
url = "2"
tokio-stream = "0.1"

[dev-dependencies]
lazy_static = "1.4"
regex = "1.5"
json = "0.12"
url = "2"
nuid = "0.3"
